version: '3.3'
services:
  app:
    container_name: 'app'
    build: .
    command: gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:40000 --timeout 400
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PW_FILE=/run/secrets/db_root_password
      - DEPLOYMENT_TYPE=production
    ports:
      - '40000:8080'
    #depends_on:
    links:
      - mysql
    secrets:
      - db_root_password
  mysql:
    container_name: mysql
    image: mysql

    restart: always
    environment:
      MYSQL_DATABASE: peoplesun_user_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    ports:
      - '40001:3306'
    secrets:
      - db_root_password
      - secret_pars
secrets:
  db_root_password:
    file: ./db_root_password.txt
  secret_pars:
    file: ./secrets/secret_py_pars.txt
