version: '3.3'
services:
  app:
    container_name: 'app'
    build: .
    command: gunicorn -w 2 -k uvicorn.workers.UvicornWorker fastapi_app.main:app --bind 0.0.0.0:40000 --timeout 1200
    # command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload --port 40000
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PW=/run/secrets/pw
    ports:
      - '40000:40000'
    #depends_on:
    links:
      - mysql
    secrets:
      - pw
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: peoplesun_user_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pw
    ports:
      - '40001:3306'
    secrets:
      - pw
secrets:
  pw:
    file: ./secrets/secret.txt
