version: '3.3'
services:
  app:
    container_name: 'app'
    build: .
    command: gunicorn -w 2 -k uvicorn.workers.UvicornWorker fastapi_app.main:app --bind 0.0.0.0:40000 --timeout 1200
    # command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload --port 40000
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PW_FILE=/run/secrets/secret_db_root_pw
      - SECRET_PARS=/run/secrets/secret_pars
    ports:
      - '40000:40000'
    #depends_on:
    links:
      - mysql
    secrets:
      - secret_db_root_pw
      - secret_pars
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: peoplesun_user_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    ports:
      - '40001:3306'
    secrets:
      - secret_db_root_pw
secrets:
  secret_db_root_pw:
    file: ./secrets/secret_db_root_pw.txt
  secret_pars:
    file: ./secrets/secret_py_pars.txt
