version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: peoplesun_user_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    expose:
      - '3306'
    ports:
      - '40001:3306'
    secrets:
      - db_root_password
  app:
    container_name: 'app'
    build: .
    command: gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8080 --timeout 400
    restart: always
    platform: linux/amd64
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PW_FILE=/run/secrets/db_root_password
    ports:
      - '40000:8080'
    depends_on:
      - mysql
    secrets:
      - db_root_password
secrets:
  db_root_password:
    file: ./db_root_password.txt